apiVersion: v1
kind: Secret
metadata:
  name: gif-transformer-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
  S3_ENDPOINT: "https://s3.amazonaws.com"
